# -*- coding: utf-8 -*-
import unicodedata
import ollama

CATEGORIAS_VALIDAS = [
    'MORADIA - Supermercado', 'MORADIA - Manutenção/Reforma', 'MORADIA - Outros',
    'CARRO - Seguro', 'CARRO - Combustível', 'CARRO - IPVA/Licenciamento',
    'CARRO - Lavagem', 'CARRO - Manutenção', 'CARRO - Outros',
    'MOTO - Seguro', 'MOTO - Combustível', 'MOTO - IPVA/Licenciamento',
    'MOTO - Lavagem', 'MOTO - Manutenção', 'MOTO - Outros',
    'BARCO - Gasolina', 'BARCO - Óleo', 'BARCO - Guardaria',
    'BARCO - Manutenção', 'BARCO - Outros',
    'D. PESSOAL - Esporte', 'D. PESSOAL - Educação', 'D. PESSOAL - Entretenimento',
    'D. PESSOAL - Restaurante', 'D. PESSOAL - Saúde', 'D. PESSOAL - Vestuário',
    'D. PESSOAL - Viagens', 'D. PESSOAL - Outros',
    'INVEST. - Renda Fixa', 'INVEST. - Ações', 'INVEST. - Fundos Imobiliários',
    'INVEST. - Títulos Públicos', 'INVEST. - Casal',
    'THALI - PIX', 'THALI - Calvin', 'THALI - Casa', 'THALI - Outros',
    'JULI - Heitor', 'JULI - Psicóloga', 'JULI - Casa', 'JULI - Outros',
    'LPC - Contador', 'LPC - Impostos',
    'SAFO ENG. - Contador', 'SAFO ENG. - Impostos', 'SAFO ENG. - PIX',
]

def _norm(s):
    s = s.upper().strip()
    return ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn')

# Mapeamento exato construído a partir do histórico 2023-2025
MAPA_EXATO = {
    '99 TECNOLOGIA*99* POP 06J': 'D. PESSOAL - Outros',
    '99 TECNOLOGIA*99* POP 10J': 'D. PESSOAL - Outros',
    '99 TECNOLOGIA*99* POP 11J': 'D. PESSOAL - Outros',
    '99 TAXI': 'D. PESSOAL - Outros',
    'A ROCA': 'THALI - Outros',
    'A98  - COMPRA SHELLBOX': 'CARRO - Combustível',
    'ABASTEC*ABASTECE AI': 'CARRO - Combustível',
    'ABERTURA DA EMPRESA': 'SAFO ENG. - PIX',
    'ACAIDAPRAIA': 'D. PESSOAL - Viagens',
    'ACESSORIOS BARCO': 'BARCO - Outros',
    'ADAPTADOR FILTRO': 'MORADIA - Manutenção/Reforma',
    'ADRIANA LIMA DA CRUZ LTDA': 'D. PESSOAL - Outros',
    'AFFETO GELATERIA': 'D. PESSOAL - Restaurante',
    'AGUA ESPRAIADA': 'CARRO - Combustível',
    'AIRBNB': 'D. PESSOAL - Viagens',
    'AIRBNB * HM5QRTXCKQ': 'BARCO - Outros',
    'AIRBNB CHILE': 'D. PESSOAL - Viagens',
    'ALL TIME MINI MERCADO': 'D. PESSOAL - Viagens',
    'ALLPARK EMPREENDIMENTOS': 'D. PESSOAL - Outros',
    # Novos - aprendidos em Mai.2026
    'ARTE FORMATTI': 'D. PESSOAL - Vestuário',
    'POSTOSETEE': 'CARRO - Combustível',
    'IBRALIA': 'D. PESSOAL - Outros',
    'PARRILINHAGASTRO': 'D. PESSOAL - Restaurante',
    'EBN*TIKTOK SH': 'MORADIA - Outros',
    'JIM.COM* MARCOS ANTONIO M': 'D. PESSOAL - Outros',
    'ANETO FOOD SERVICE': 'D. PESSOAL - Restaurante',
    'RESTAURANTEKOME': 'D. PESSOAL - Restaurante',
    'RGB BAR E RESTAURANTE': 'D. PESSOAL - Restaurante',
    'O PANELINHA RESTAURANTE': 'D. PESSOAL - Restaurante',
    'MERCADOLIVRE*RARVELSTORE': 'D. PESSOAL - Outros',
    'MERCADOLIVRE*HIDRACOM': 'MORADIA - Manutenção/Reforma',
    'MERCADOLIVRE*CASAFORTEMF': 'MORADIA - Manutenção/Reforma',
    'MERCADOLIVRE*OTTOPARTS': 'CARRO - Manutenção',
    'MERCADOLIVRE*TUBARAOCENTE': 'D. PESSOAL - Outros',
    'PROL PARK': 'CARRO - Outros',
    'ESTACENTER SSC': 'CARRO - Outros',
    'DROGASIL1642': 'D. PESSOAL - Saúde',
    'DIPALU ESFIHARIA': 'D. PESSOAL - Restaurante',
    'LABORATORIO EMBRA': 'D. PESSOAL - Saúde',
    'REMEDIOPOPULAR': 'D. PESSOAL - Saúde',
    'PETLANDCANAL6': 'THALI - Calvin',
    'IFD*BRASAMAR PICANHARIA E': 'D. PESSOAL - Restaurante',
    'IFD*VISTA DA BARRA LAN': 'D. PESSOAL - Restaurante',
    'IFD*BR': 'D. PESSOAL - Restaurante',
    'IFD*DBOA COMERCIO DE A': 'D. PESSOAL - Restaurante',
    'ALMOCO': 'D. PESSOAL - Viagens',
    'ALMOCO BRUNO (KOJI)': 'D. PESSOAL - Restaurante',
    'ALMOCO MARAGOGI': 'D. PESSOAL - Viagens',
    'ALMOCO SP': 'D. PESSOAL - Restaurante',
    'AMAZON BR': 'D. PESSOAL - Outros',
    'AMAZON BR TALHERES': 'MORADIA - Outros',
    'AMAZON MARKETPLACE': 'D. PESSOAL - Outros',
    'AMAZONMKTPLC*BERTSCOME': 'MORADIA - Outros',
    'AMBIENTE DO SABER': 'D. PESSOAL - Entretenimento',
    'ANDRADEYS PARK': 'D. PESSOAL - Viagens',
    'ANGELITA DO PRADO': 'D. PESSOAL - Restaurante',
    'ANUNCIO CARRO WEBMOTORS': 'CARRO - Outros',
    'AP BRASIL 2005 CONV': 'D. PESSOAL - Outros',
    'APPLE.COM/BILL': 'D. PESSOAL - Outros',
    'APTO CLANDESTINO': 'D. PESSOAL - Restaurante',
    'ASPIRADOR': 'MORADIA - Outros',
    'ASSAI ATACADISTA': 'MORADIA - Supermercado',
    'ASSOCIACAO ATLETICA DO': 'D. PESSOAL - Outros',
    'ATIVA HOUSE': 'D. PESSOAL - Entretenimento',
    'AUTENTICA': 'BARCO - Outros',
    'AUTO POSTO': 'CARRO - Combustível',
    'AUTO POSTO 3 IRMAOS': 'D. PESSOAL - Viagens',
    'AUTO POSTO ESTRELA SA': 'MOTO - Combustível',
    'AUTO POSTO FERRY BOAT': 'BARCO - Gasolina',
    'AUTO POSTO ILHA NEGRA': 'CARRO - Combustível',
    'AUTO POSTO IRMAOS': 'MOTO - Combustível',
    'AUTO POSTO IRMAOS MIGU': 'CARRO - Combustível',
    'AUTO POSTO LUNAR LTDA': 'CARRO - Combustível',
    'AUTO POSTO OCEANO ATLA': 'MOTO - Combustível',
    'AUTO POSTO PEDRO': 'MOTO - Combustível',
    'AUTO POSTO SACO D': 'D. PESSOAL - Viagens',
    'AUTO POSTO VALONG': 'CARRO - Combustível',
    'AUTO POSTO VERANEIO': 'MOTO - Combustível',
    'AUTOZONE': 'BARCO - Manutenção',
    'AV ANA COSTA': 'D. PESSOAL - Outros',
    'AZUL': 'D. PESSOAL - Viagens',
    'AZUL SEGUROS': 'CARRO - Seguro',
    'AZULGRGR4B': 'D. PESSOAL - Viagens',
    'BACIODILATTE-LJ0114': 'D. PESSOAL - Restaurante',
    'BALA': 'D. PESSOAL - Outros',
    'BALENA CLUB': 'D. PESSOAL - Viagens',
    'BALSA': 'CARRO - Outros',
    'BANCA SOBRE AS ONDAS': 'D. PESSOAL - Outros',
    'BANCO MOTO': 'MOTO - Manutenção',
    'BANDEIRANTES': 'CARRO - Combustível',
    'BAR DO CARLINHOS II': 'D. PESSOAL - Restaurante',
    'BAR DOS AMIGOS GRILL': 'D. PESSOAL - Restaurante',
    'BAR E ACAI LANCHES': 'D. PESSOAL - Restaurante',
    'BAR E RESTAURANTE': 'D. PESSOAL - Restaurante',
    'BAR E RESTAURANTE JE': 'D. PESSOAL - Restaurante',
    'BARCO HEITOR': 'JULI - Heitor',
    'BARCO PARATY': 'D. PESSOAL - Viagens',
    'BARCO TRILHA PARATY': 'D. PESSOAL - Viagens',
    'BARROCA': 'D. PESSOAL - Restaurante',
    'BAT. BAND. LUZ': 'BARCO - Manutenção',
    'BATERIA E ENGATE BARCO': 'BARCO - Outros',
    'BERLINF*ESTRELA SANTIS': 'MORADIA - Supermercado',
    'BICICLETARIA CAJUEIRO': 'D. PESSOAL - Outros',
    'BIG PIZZA': 'D. PESSOAL - Restaurante',
    'BIG PIZZAS': 'D. PESSOAL - Restaurante',
    'BIG PIZZAS MOROZETTI &': 'D. PESSOAL - Restaurante',
    'BIN MATERIAIS': 'MORADIA - Outros',
    'BIQUINI THALI': 'D. PESSOAL - Outros',
    'BLABLACAR': 'THALI - PIX',
    'BLUSA': 'D. PESSOAL - Vestuário',
    'BLUSA CASAMENTO BRUNO': 'D. PESSOAL - Vestuário',
    'BOLETO APTO': 'INVEST. - Casal',
    'BOLAO LATINA': 'D. PESSOAL - Outros',
    'BOLAO LPC': 'D. PESSOAL - Outros',
    'BOTECO LOUNGE HOU': 'D. PESSOAL - Restaurante',
    'BOTECODOGONZA': 'D. PESSOAL - Restaurante',
    'BP ILHABELA': 'BARCO - Outros',
    'BRAZIL HIGHWAY 00': 'D. PESSOAL - Restaurante',
    'BRITANIA OFICIAL': 'D. PESSOAL - Outros',
    'BROWNIE': 'D. PESSOAL - Restaurante',
    'BUTECODOJOHN': 'D. PESSOAL - Restaurante',
    'C A AGUA ESPRAIAD': 'D. PESSOAL - Restaurante',
    'C C MENDES DOS SANTOS': 'D. PESSOAL - Restaurante',
    'C&A': 'D. PESSOAL - Vestuário',
    'C&A (PRESENTE TIA)': 'D. PESSOAL - Outros',
    'CABO DE REDE E TRANSFORMADOR': 'THALI - Casa',
    'CABO IPHONE': 'D. PESSOAL - Outros',
    'CACAU SHOW': 'D. PESSOAL - Restaurante',
    'CACAU SHOW MAYRA': 'D. PESSOAL - Viagens',
    'CACHACA HOUSE': 'D. PESSOAL - Restaurante',
    'CALDO DE CANA': 'D. PESSOAL - Restaurante',
    'CALOPSYTA COMERCIO': 'CARRO - Combustível',
    'CAMINHO DO OURO DE PAR': 'CARRO - Combustível',
    'CANAL DA ENG (CYPECAD)': 'D. PESSOAL - Educação',
    'CANTINA LILIANA': 'D. PESSOAL - Restaurante',
    'CANTO DO MAR II': 'D. PESSOAL - Viagens',
    'CARREFOUR BIG SANTOS': 'MORADIA - Supermercado',
    'CARREFOUR EXPRESS': 'D. PESSOAL - Restaurante',
    'CASA DE FERRAG P PRAIA': 'MORADIA - Manutenção/Reforma',
    'CASA DE SUCOS GALERIA': 'D. PESSOAL - Restaurante',
    'CASA DOS PARAFUSOS': 'BARCO - Manutenção',
    'CASA FERNANDO': 'MORADIA - Outros',
    'CASA ILHABELA - BRUNO E MARI': 'D. PESSOAL - Viagens',
    'CASARIA EMPORIO E CONV': 'D. PESSOAL - Restaurante',
    'CEA AMIGO SECRETO': 'D. PESSOAL - Entretenimento',
    'CENTER CASTILHO MATPCO': 'MORADIA - Manutenção/Reforma',
    'CENTROAUTOMOTIVO': 'CARRO - Outros',
    'CERTIFICADO DIGITAL': 'LPC - Impostos',
    'CHAVEIRO PONTA DA PRAIA': 'D. PESSOAL - Outros',
    'CHAVES E ADAPT FILTRO': 'MORADIA - Outros',
    'CHIQUINHOS TRABULSI': 'D. PESSOAL - Restaurante',
    'CINEMA GUARUJA': 'D. PESSOAL - Entretenimento',
    'CIRURGICA BORGES': 'D. PESSOAL - Saúde',
    'CLASSIC PIZZAS': 'D. PESSOAL - Restaurante',
    'CLUB MEN': 'D. PESSOAL - Outros',
    'CLUB MEN BOQUEIRAO': 'D. PESSOAL - Outros',
    'CLUB MEN PRAIAMAR': 'D. PESSOAL - Outros',
    'COBASI': 'THALI - Calvin',
    'COBASI MORUNGABA': 'THALI - Calvin',
    'COBASI SANTOS AFO': 'THALI - Calvin',
    'COBASI SANTOS AFONSO P': 'THALI - Calvin',
    'COCO': 'D. PESSOAL - Restaurante',
    'COMERCIAL TRUCK PECAS': 'BARCO - Manutenção',
    'COMIDA': 'D. PESSOAL - Restaurante',
    'COMIDA HOTEL CAIO/CAMILA': 'D. PESSOAL - Viagens',
    'COMIDA MORUNGABA': 'D. PESSOAL - Viagens',
    'COMIDA RUA': 'D. PESSOAL - Restaurante',
    'CONCESSIONARIA RO': 'D. PESSOAL - Viagens',
    'CONCHA Y TORO': 'D. PESSOAL - Viagens',
    'CONDOR PARANAGUA': 'D. PESSOAL - Viagens',
    'CONFRA LPC': 'D. PESSOAL - Outros',
    'CONSERTO CIVIC': 'CARRO - Manutenção',
    'CONSERTO MAQUINA': 'MORADIA - Manutenção/Reforma',
    'CONSTRUDECOR S A': 'MORADIA - Manutenção/Reforma',
    'CONSTRUMADE': 'D. PESSOAL - Restaurante',
    'CONTA DE LUZ': 'MORADIA - Outros',
    'CONV PORTAL DE SANTOS': 'D. PESSOAL - Restaurante',
    'CONVENIENCIA': 'D. PESSOAL - Restaurante',
    'COPIADORA MAUA': 'D. PESSOAL - Outros',
    'COPY.COM': 'D. PESSOAL - Outros',
    'CORANTE THALI': 'THALI - Casa',
    'COUTO (BROCA)': 'BARCO - Manutenção',
    'CREA': 'D. PESSOAL - Outros',
    'CREATINA': 'D. PESSOAL - Outros',
    'CREPERIA DA PRAIA II': 'D. PESSOAL - Restaurante',
    'CRI CRI MOTOS': 'MOTO - Manutenção',
    'CRUZ DE MALTA MAT CON': 'MORADIA - Manutenção/Reforma',
    'CURSO CIVIL 3D': 'D. PESSOAL - Educação',
    'CURSO DE PATOLOGIAS': 'D. PESSOAL - Educação',
    'CURSO PATOLOGIAS': 'D. PESSOAL - Educação',
    'CURSO RIGGING': 'D. PESSOAL - Educação',
    'DA BALANCA': 'D. PESSOAL - Restaurante',
    'DALAPA': 'D. PESSOAL - Outros',
    'DBOA QUIOSQUE': 'D. PESSOAL - Restaurante',
    'DECOLAR': 'D. PESSOAL - Viagens',
    'DELTAGLOBALHISTORICAR': 'D. PESSOAL - Outros',
    'DESEJO DE CAFE': 'D. PESSOAL - Restaurante',
    'DESEMPENO RODA MOTO': 'MOTO - Manutenção',
    'DESPEDIDA CAIO': 'D. PESSOAL - Outros',
    'DIFERENTE II': 'D. PESSOAL - Restaurante',
    'DINHEIRO EMPRESTADO': 'THALI - PIX',
    'DL *ALIPAY ALIPAY BRAS': 'MORADIA - Outros',
    'DM*UDEMY': 'D. PESSOAL - Educação',
    'DOCARIADAVIDLTDA': 'D. PESSOAL - Restaurante',
    'DOCE LPC': 'D. PESSOAL - Restaurante',
    'DOCES DAVID': 'D. PESSOAL - Restaurante',
    'DOCUMENTACAO DO HOBIE': 'BARCO - Outros',
    'DOCUMENTO BARCO': 'BARCO - Outros',
    'DONA ALICE PADARIA E C': 'D. PESSOAL - Restaurante',
    'DONNA ANDREA RESTAURAN': 'D. PESSOAL - Restaurante',
    'DOSETTE CAFE': 'D. PESSOAL - Restaurante',
    'DOUGLAS GARAGE': 'CARRO - Manutenção',
    'DRIVE GOOGLE': 'D. PESSOAL - Outros',
    'DROGARIA SAO PAULO': 'D. PESSOAL - Saúde',
    'DROGARIA SAO PAULO 228': 'D. PESSOAL - Saúde',
    'DROGARIA SAO PAULO 240': 'D. PESSOAL - Saúde',
    'DROGARIA SAO PAULO SA': 'D. PESSOAL - Saúde',
    'DROGARIAS SAO PAULO': 'D. PESSOAL - Saúde',
    'DROGASIL': 'D. PESSOAL - Saúde',
    'DUDAARTIGOS': 'D. PESSOAL - Outros',
    'EBN    *TIKTOK SHOP': 'MORADIA - Outros',
    'EDA SHOWS': 'D. PESSOAL - Viagens',
    'ELAINESINVAL': 'D. PESSOAL - Viagens',
    'ELVIS FERREIRA GUIMARA': 'D. PESSOAL - Restaurante',
    'EMBALAGENS PARA OLEO': 'BARCO - Outros',
    'EMIRADOS': 'D. PESSOAL - Viagens',
    'EMPORIO MONTE BEL': 'D. PESSOAL - Restaurante',
    'ENCAIXES': 'BARCO - Outros',
    'ESCRITURA BOI': 'D. PESSOAL - Outros',
    'ESCUNA KATOOSH': 'D. PESSOAL - Entretenimento',
    'ESFIHA IMIGRANTES': 'D. PESSOAL - Entretenimento',
    'ESQUINA DAS CAPAS': 'D. PESSOAL - Outros',
    'ESTACIONAMENTO': 'D. PESSOAL - Viagens',
    'ESTACIONAMENTO PARATY': 'D. PESSOAL - Viagens',
    'ESTACIONAMENTODA': 'CARRO - Outros',
    'ESTANCIA CAFE': 'D. PESSOAL - Viagens',
    'ESTRELA DE OURO': 'D. PESSOAL - Restaurante',
    'ESTRELA OURO': 'D. PESSOAL - Restaurante',
    'ESTRELA OURO FUTEBO': 'D. PESSOAL - Restaurante',
    'ESTRELA SANTISTA': 'D. PESSOAL - Viagens',
    'ESTRELASANTISTA': 'CARRO - Combustível',
    'FARMACIA': 'D. PESSOAL - Saúde',
    'FAXINA DE CASA': 'MORADIA - Outros',
    'FESTA KATOOSH': 'D. PESSOAL - Outros',
    'FILTRO DE AGUA': 'MORADIA - Outros',
    'FITAS BARCO': 'BARCO - Outros',
    'FLORICULTURA IGARI': 'D. PESSOAL - Outros',
    'FOGAO DE MINAS': 'D. PESSOAL - Restaurante',
    'FOGO DE MINAS': 'D. PESSOAL - Restaurante',
    'FONE DE OUVIDO': 'D. PESSOAL - Outros',
    'FONE E LUB MOTO': 'MOTO - Manutenção',
    'FORMIGUINHA': 'D. PESSOAL - Outros',
    'FORNO CAICARA': 'D. PESSOAL - Restaurante',
    'FORTE DA BARRA': 'MORADIA - Supermercado',
    'FORTEDABARRA': 'MORADIA - Supermercado',
    'FRANGO ASSADO': 'D. PESSOAL - Viagens',
    'FRANGO ASSADO POS': 'CARRO - Combustível',
    'FREIO CIVIC': 'CARRO - Manutenção',
    'FRIGIDEIRA': 'MORADIA - Outros',
    'FUI GOSTEI': 'D. PESSOAL - Viagens',
    'FUNILARIA': 'CARRO - Manutenção',
    'GALOQUENTE3': 'D. PESSOAL - Restaurante',
    'GAS MENEZES E MACEDO L': 'MORADIA - Outros',
    'GASOLINA': 'CARRO - Combustível',
    'GASOLINA MARAGOGI': 'D. PESSOAL - Viagens',
    'GAVIAO': 'THALI - Casa',
    'GBCHOPERIAE': 'D. PESSOAL - Restaurante',
    'GELO PARATY': 'D. PESSOAL - Viagens',
    'GIANI BUFFET': 'D. PESSOAL - Restaurante',
    'GMENDES': 'D. PESSOAL - Outros',
    'GMENDES ESTACIONA': 'MOTO - Outros',
    'GRAAL': 'D. PESSOAL - Viagens',
    'GRAN GIANMA COMERCIO D': 'D. PESSOAL - Restaurante',
    'GRAVATA BRUNO': 'D. PESSOAL - Outros',
    'GREEN PARK': 'CARRO - Outros',
    'GUARDARIA E LAVAGEM COROLLA': 'D. PESSOAL - Outros',
    'GUARUJOIA': 'D. PESSOAL - Outros',
    'GUSTAVOOLIVEIRA': 'D. PESSOAL - Outros',
    'H A C E SILVA MATERIAIS': 'MORADIA - Manutenção/Reforma',
    'HAMBURGUERIA': 'D. PESSOAL - Restaurante',
    'HAVAIANAS': 'JULI - Heitor',
    'HERING AV DOS BANCARIO': 'D. PESSOAL - Vestuário',
    'HIPERBARICA': 'D. PESSOAL - Saúde',
    'HOTTEL COMPANY BAR': 'D. PESSOAL - Restaurante',
    'HTM    *ENPVITALICIO': 'D. PESSOAL - Educação',
    'HTM*CANALDAENG': 'D. PESSOAL - Educação',
    'IACS PONTA DA PRA': 'D. PESSOAL - Saúde',
    'IDEAL PNEUS': 'MOTO - Outros',
    'IFD         *ZAMP SA': 'D. PESSOAL - Restaurante',
    'IFD*A BIG PIZZA DE SANTOS': 'D. PESSOAL - Restaurante',
    'IFD*AMANDA MAYUME VIAN': 'D. PESSOAL - Restaurante',
    'IFD*DBOA COMERCIO DE ALIM': 'D. PESSOAL - Restaurante',
    'IFD*DROGARIA SAO PAULO': 'D. PESSOAL - Saúde',
    'IFD*ESFIHARIA SANTA RITA': 'D. PESSOAL - Restaurante',
    'IFD*GVS RESTAURANTE BAR B': 'D. PESSOAL - Restaurante',
    'IFD*IFOOD': 'D. PESSOAL - Outros',
    'IFD*IFOOD CLUB': 'D. PESSOAL - Restaurante',
    'IFD*KOME DELIVERY MOEMA L': 'D. PESSOAL - Restaurante',
    'IFD*PAFER PUGLISI COME': 'D. PESSOAL - Restaurante',
    'IFD*PIZZA CESAR SANTOS LT': 'D. PESSOAL - Restaurante',
    'IFD*PURAVIDA SUSHI LTDA.': 'D. PESSOAL - Restaurante',
    'IFD*RAFAEL SILVA POZO 337': 'D. PESSOAL - Restaurante',
    'IFD*REDE INTEGRADA DE': 'MORADIA - Supermercado',
    'IFD*RESTAURANTE E PIZZARI': 'D. PESSOAL - Restaurante',
    'IFD*RESTAURANTE ROTA NORD': 'D. PESSOAL - Restaurante',
    'IFD*TEMAKERIA TROPICAL LT': 'D. PESSOAL - Restaurante',
    'IFOOD': 'D. PESSOAL - Restaurante',
    'IFOOD (RENATA)': 'D. PESSOAL - Restaurante',
    'IFOOD CLUB': 'D. PESSOAL - Restaurante',
    'IFOOD DAGS (BRUNO E MARI)': 'D. PESSOAL - Restaurante',
    'IFOOD ROTA NORDESTINA': 'D. PESSOAL - Restaurante',
    'ILHABELA POSTO SERVICO': 'BARCO - Outros',
    'ILHABELA REPUBLIC': 'D. PESSOAL - Viagens',
    'IMPOSTOS MUNICIPAIS': 'LPC - Impostos',
    'IMPOSTOS SEFAZ': 'LPC - Impostos',
    'INDUSTRIA DE PANIFICAC. (CAROLINA)': 'D. PESSOAL - Restaurante',
    'INSCR. REGATA': 'D. PESSOAL - Entretenimento',
    'INSIDER COMERCIO E CON': 'D. PESSOAL - Vestuário',
    'INSTALACAO MOTOR': 'BARCO - Manutenção',
    'INVESTIMENTO (RICO)': 'INVEST. - Ações',
    'IPHONE': 'D. PESSOAL - Outros',
    'IPVA MOTO - PARCELA TOTAL': 'MOTO - IPVA/Licenciamento',
    'ITALIA KART EVENTOS': 'D. PESSOAL - Restaurante',
    'JANTAR NA VO': 'D. PESSOAL - Restaurante',
    'JAPA ACAI': 'D. PESSOAL - Restaurante',
    'JJF COMERCIO DE MATERI': 'D. PESSOAL - Outros',
    'JOSE ERNANDE SANT': 'D. PESSOAL - Restaurante',
    'JR MOTOS': 'MOTO - Manutenção',
    'JUSCELIRIBEIRODA': 'D. PESSOAL - Restaurante',
    'KAHU PET': 'D. PESSOAL - Outros',
    'KALLAN - K03 - SANTOS': 'D. PESSOAL - Vestuário',
    'KART': 'D. PESSOAL - Entretenimento',
    'KATARINA BAR': 'D. PESSOAL - Entretenimento',
    'KEETA JAPA': 'D. PESSOAL - Restaurante',
    'KIDS PIZZA BAR   RESTAURA': 'D. PESSOAL - Restaurante',
    'KOJI GOURMET': 'D. PESSOAL - Restaurante',
    'KOMBOSA SHAKE': 'D. PESSOAL - Restaurante',
    'KOMILAO': 'D. PESSOAL - Restaurante',
    'KOMPRY BATERIAS': 'BARCO - Outros',
    'KOPENHAGEN': 'D. PESSOAL - Restaurante',
    'KUCHOS': 'D. PESSOAL - Viagens',
    'LA CANIZA': 'CARRO - Combustível',
    'LADO BURGER': 'D. PESSOAL - Restaurante',
    'LAGO AZUL': 'CARRO - Combustível',
    'LAMPADA + CINTA HELERMAN': 'MORADIA - Outros',
    'LAMPADAS': 'BARCO - Outros',
    'LANCHA CAIO': 'D. PESSOAL - Entretenimento',
    'LANCHE LPC': 'D. PESSOAL - Restaurante',
    'LAVA RAPIDO': 'CARRO - Lavagem',
    'LAVAGEM': 'CARRO - Lavagem',
    'LAVAGEM ILHABELA': 'CARRO - Lavagem',
    'LAVAGEM MINI': 'CARRO - Lavagem',
    'LAZER HOPI HARI': 'D. PESSOAL - Viagens',
    'LEROY MERLIN - BRUNO': 'D. PESSOAL - Outros',
    'LICENCIAMENTO CARRO': 'CARRO - IPVA/Licenciamento',
    'LICENCIAMENTO MOTO': 'MOTO - IPVA/Licenciamento',
    'LIMPEZA CASA': 'MORADIA - Outros',
    'LIN YU CHIEH': 'D. PESSOAL - Viagens',
    'LINDT': 'D. PESSOAL - Outros',
    'LIVRARIA MARTINS': 'D. PESSOAL - Outros',
    'LIXAS DREMMEL': 'MORADIA - Outros',
    'LOJA DE CONVENIENCIA M': 'D. PESSOAL - Viagens',
    'LOJAS MARI': 'THALI - Outros',
    'LOUSA E CANETAS': 'D. PESSOAL - Outros',
    'LUB MOTO E FONE': 'MOTO - Manutenção',
    'LUVA KAIROS': 'D. PESSOAL - Esporte',
    'LYNCON': 'D. PESSOAL - Restaurante',
    'LYNCON PAO DE QJO': 'D. PESSOAL - Restaurante',
    'M A L U CACAU': 'D. PESSOAL - Outros',
    'MACATHUR PASSEIO': 'D. PESSOAL - Viagens',
    'MADE AUTORAL DELIVERY I': 'D. PESSOAL - Restaurante',
    'MAGALU LONA': 'BARCO - Outros',
    'MAGAZINE LUIZA (TENIS ACAD)': 'D. PESSOAL - Vestuário',
    'MAGIC MEDIC': 'D. PESSOAL - Outros',
    'MAIS BRINQUEDOS EIRELI': 'D. PESSOAL - Outros',
    'MAIS GELATERIA': 'D. PESSOAL - Restaurante',
    'MAK8 ESTACIONAMENTOS': 'CARRO - Outros',
    'MANIA DE CHURRASCO': 'D. PESSOAL - Restaurante',
    'MANJERONA': 'D. PESSOAL - Restaurante',
    'MANOELMESSIAS': 'D. PESSOAL - Restaurante',
    'MANUBE CERVEJARIA': 'D. PESSOAL - Outros',
    'MANUTENCAO CARRO': 'CARRO - Manutenção',
    'MANUTENCAO MOTOR': 'BARCO - Manutenção',
    'MAQUIAGEM CAS. BRUNO': 'THALI - PIX',
    'MARATHON': 'D. PESSOAL - Saúde',
    'MARIA DE FATIMA S': 'D. PESSOAL - Outros',
    'MARIA FRANCISCA DE LIM': 'D. PESSOAL - Viagens',
    'MARIATAXI': 'D. PESSOAL - Outros',
    'MARINA': 'BARCO - Guardaria',
    'MARINA GUADALUPE MATHIA': 'D. PESSOAL - Viagens',
    'MASSIMA LAVANDERIA': 'MORADIA - Outros',
    'MC DONALD S': 'D. PESSOAL - Restaurante',
    'MC DONALDS': 'D. PESSOAL - Restaurante',
    'MC DONALDS GJR': 'D. PESSOAL - Restaurante',
    'MC DONNALDS SP': 'D. PESSOAL - Restaurante',
    'MEI': 'D. PESSOAL - Outros',
    'MERCADO DO SORVETE': 'D. PESSOAL - Restaurante',
    'MERCADO GAUCHO': 'D. PESSOAL - Viagens',
    'MERCADO MODELO2': 'D. PESSOAL - Restaurante',
    'MERCADO POR DO SOL': 'MORADIA - Supermercado',
    'MERCADOLIVRE*2PRODUTOS': 'MOTO - Outros',
    'MERCADOLIVRE*3PRODUTOS': 'D. PESSOAL - Outros',
    'MERCADOLIVRE*4PRODUTOS': 'MOTO - Manutenção',
    'MERCADOLIVRE*5PRODUTOS': 'MORADIA - Outros',
    'MERCADOLIVRE*EHNCGAIOLAS': 'MORADIA - Outros',
    'MERCADOLIVRE*JJMOTORCY': 'MOTO - Manutenção',
    'MERCADOLIVRE*MERCADOLIVRE': 'MORADIA - Outros',
    'MERCADOLIVRE*PORTONAUTICO': 'BARCO - Outros',
    'MERCADOPAGO*3PRODUTOS': 'MORADIA - Outros',
    'MERCADOPAGO*RESTAURANTERO': 'D. PESSOAL - Restaurante',
    'MERCADOPAGO*ZAROC': 'D. PESSOAL - Vestuário',
    'MILK MOO': 'D. PESSOAL - Restaurante',
    'MILK SHAKE DNL LTDA': 'D. PESSOAL - Restaurante',
    'MILKY MOO GONZAGA': 'D. PESSOAL - Restaurante',
    'MINUTO PA': 'D. PESSOAL - Viagens',
    'MINUTO PA 1430': 'MORADIA - Supermercado',
    'MINUTO PA-5430': 'MORADIA - Supermercado',
    'MINUTO PAO 1430 MARIO': 'MORADIA - Supermercado',
    'MINUTO PAO DE ACUCAR': 'MORADIA - Supermercado',
    'MIXER': 'MORADIA - Outros',
    'ML': 'MOTO - Manutenção',
    'ML CUECAS': 'D. PESSOAL - Vestuário',
    'ML FIO BARCO': 'BARCO - Manutenção',
    'ML POWER BANKING': 'D. PESSOAL - Outros',
    'ML PULSEIRA E MANOPLA': 'MOTO - Outros',
    'ML SACOS DE VACUO': 'D. PESSOAL - Viagens',
    'ML WHEY': 'D. PESSOAL - Saúde',
    'ML OLEO 2T (3 UNID.)': 'BARCO - Outros',
    'MONTANICASAE': 'MORADIA - Manutenção/Reforma',
    'MORIFARMA PARANAGUA CTO': 'D. PESSOAL - Viagens',
    'MOTO E COISAS PARA CASA': 'MOTO - Manutenção',
    'MOTOR': 'BARCO - Outros',
    'MP*ACAIDAILHA': 'D. PESSOAL - Restaurante',
    'MP*ALIPAYBRASILMEIOSDEPAG': 'D. PESSOAL - Restaurante',
    'MP*DPAG7VIEIRA': 'D. PESSOAL - Outros',
    'MP*GISELLEROSA': 'MORADIA - Outros',
    'MP*PROGRAMATUBED': 'D. PESSOAL - Outros',
    'MPA 1453 ANA COSTA': 'D. PESSOAL - Outros',
    'MULTICOISAS VARANASI': 'MORADIA - Outros',
    'MUNDO DO GAS': 'MORADIA - Outros',
    'N S ANDRADE PADARIA M': 'D. PESSOAL - Restaurante',
    'NELSON P PICCOLO': 'BARCO - Manutenção',
    'NISSEI*555794700': 'D. PESSOAL - Saúde',
    'NOSSO HORTIFRUTI': 'D. PESSOAL - Restaurante',
    'NOVA NEVILLE': 'D. PESSOAL - Outros',
    'ONTIME KAJIYA': 'D. PESSOAL - Restaurante',
    'OXXO BRASILIA': 'D. PESSOAL - Restaurante',
    'OXXO EPITACIO PES': 'D. PESSOAL - Restaurante',
    'OXXO EPITACIO PESSOA': 'D. PESSOAL - Outros',
    'OZ FORNERIA': 'D. PESSOAL - Restaurante',
    'PADARIA A TRIGUEIRA': 'D. PESSOAL - Restaurante',
    'PADRELA': 'D. PESSOAL - Restaurante',
    'PADRELA (BOLO MARI)': 'D. PESSOAL - Entretenimento',
    'PADRELA PANIFICAD': 'D. PESSOAL - Restaurante',
    'PAG*BEATRIZAPARECIDA': 'D. PESSOAL - Outros',
    'PAG*DALILAMATOSDE': 'D. PESSOAL - Outros',
    'PAG*DEPOSITOSOARES': 'D. PESSOAL - Outros',
    'PAG*FORTEDABARRA': 'D. PESSOAL - Outros',
    'PAG*KENIANOBREBUFFET': 'D. PESSOAL - Viagens',
    'PAG*MANOELMESSIAS': 'D. PESSOAL - Outros',
    'PAG*MOTIRO': 'D. PESSOAL - Entretenimento',
    'PAG*PADRELA': 'D. PESSOAL - Restaurante',
    'PAG*POSTODE': 'MOTO - Combustível',
    'PAGAMENTO VITOR': 'LPC - Contador',
    'PANDOCA DO JJ': 'D. PESSOAL - Restaurante',
    'PANIF JUQUEHY': 'D. PESSOAL - Restaurante',
    'PANIFICAD SANTA HELENA': 'D. PESSOAL - Restaurante',
    'PANIFICADORA': 'D. PESSOAL - Restaurante',
    'PANIFICADORA CAIC': 'D. PESSOAL - Restaurante',
    'PANIFICADORA CECI': 'D. PESSOAL - Restaurante',
    'PANIFICADORA REI DO TR': 'D. PESSOAL - Restaurante',
    'PANIFICADORA UNIVERSO': 'D. PESSOAL - Restaurante',
    'PARAFUSOS': 'MORADIA - Manutenção/Reforma',
    'PASCASIOGUSTAO': 'MORADIA - Outros',
    'PASSAGEM CHILE': 'D. PESSOAL - Viagens',
    'PASTEL': 'D. PESSOAL - Restaurante',
    'PASTEL DA ISA': 'D. PESSOAL - Restaurante',
    'PATOLOGIAS': 'D. PESSOAL - Educação',
    'PEDRABAIANAIII': 'D. PESSOAL - Restaurante',
    'PELICULA THALI': 'THALI - Outros',
    'PENSAO SANTO ANTO': 'D. PESSOAL - Restaurante',
    'PETLOVE': 'THALI - Calvin',
    'PECAS CARRETA HOBBIE': 'BARCO - Manutenção',
    'PECAS HOBIECAT': 'BARCO - Guardaria',
    'PINCA DE FREIO': 'CARRO - Manutenção',
    'PINCA DE FREIO CARRO': 'CARRO - Manutenção',
    'PIPAPIZZASEPASTAS': 'D. PESSOAL - Restaurante',
    'PIPOCAS': 'D. PESSOAL - Restaurante',
    'PIRATAS BURGER': 'D. PESSOAL - Restaurante',
    'PIX LYNCON': 'D. PESSOAL - Outros',
    'PIX THALI': 'THALI - PIX',
    'PIZZA': 'D. PESSOAL - Restaurante',
    'PNEU': 'CARRO - Manutenção',
    'PNEU MOTO': 'MOTO - Manutenção',
    'PNEUS MOTO': 'MOTO - Manutenção',
    'PODOLOGA': 'D. PESSOAL - Saúde',
    'PONCE PARK': 'D. PESSOAL - Viagens',
    'PONTO DO PEIXE': 'D. PESSOAL - Restaurante',
    'PORTO DOS BROWNIES': 'D. PESSOAL - Restaurante',
    'POSTO 2648 SANTOS': 'CARRO - Combustível',
    'POSTO ALCATRAZES': 'MOTO - Combustível',
    'POSTO ASTURIAS GUARUJA': 'CARRO - Combustível',
    'POSTO AVENIDA': 'CARRO - Combustível',
    'POSTO DE SERVICOS TRAV': 'CARRO - Combustível',
    'POSTO ESTANCIA': 'CARRO - Combustível',
    'POSTO ILHA GUARUJA': 'BARCO - Outros',
    'POSTO PORTAL DE SANTOS': 'MOTO - Combustível',
    'POSTO TANGERINO LTDA': 'BARCO - Gasolina',
    'POSTOASTURIAS': 'CARRO - Combustível',
    'POUSADA ITACOA': 'D. PESSOAL - Viagens',
    'PRESENTE HEITOR': 'JULI - Heitor',
    'PRESENTE MARAGOGI': 'D. PESSOAL - Viagens',
    'PRIME BOTTLES LTDA': 'D. PESSOAL - Restaurante',
    'PROTETOR SOLAR': 'D. PESSOAL - Saúde',
    'PSICOLOGA': 'D. PESSOAL - Saúde',
    'PSICOLOGA JU': 'JULI - Psicóloga',
    'PURA VIDA SUSHI': 'D. PESSOAL - Restaurante',
    'PAO DE ACUCAR': 'MORADIA - Supermercado',
    'QCY BRASIL LTDA': 'D. PESSOAL - Entretenimento',
    'RAIA DROGASIL SA': 'D. PESSOAL - Saúde',
    'RAIA2098': 'D. PESSOAL - Saúde',
    'RAIADROGASILSA': 'D. PESSOAL - Saúde',
    'RACAO DOGS': 'MORADIA - Outros',
    'RBS - RODOVIA BANDEIRA': 'D. PESSOAL - Viagens',
    'RECANTO DAS ANDORINHAS': 'D. PESSOAL - Viagens',
    'RECEITA FEDERAL': 'LPC - Impostos',
    'RECONHECER FIRMA (CARRO)': 'CARRO - Outros',
    'REDE TOP COMERCIO DE G': 'D. PESSOAL - Restaurante',
    'REI DO TRIGO': 'D. PESSOAL - Restaurante',
    'RENATA RODRIGUES DA GAMA': 'D. PESSOAL - Restaurante',
    'RENNER': 'D. PESSOAL - Vestuário',
    'REPARO BARCO': 'BARCO - Manutenção',
    'RESTAURANTE': 'D. PESSOAL - Restaurante',
    'RESTAURANTE CAICARA.': 'D. PESSOAL - Restaurante',
    'RESTAURANTE FAZ ITATIB': 'D. PESSOAL - Restaurante',
    'RESTAURANTE PELAN': 'D. PESSOAL - Viagens',
    'RESTAURANTERO': 'D. PESSOAL - Restaurante',
    'REVISAO MOTO': 'MOTO - Manutenção',
    'RIACHUELO': 'D. PESSOAL - Outros',
    'RIACHUELO-FILIAL.074': 'D. PESSOAL - Vestuário',
    'ROBO ASPIRADOR': 'MORADIA - Outros',
    'RONILDOGOMESSILVA': 'D. PESSOAL - Viagens',
    'ROTATIVO': 'D. PESSOAL - Viagens',
    'ROTATIVO PARATY': 'D. PESSOAL - Viagens',
    'ROUPA DE NEVE': 'D. PESSOAL - Viagens',
    'SALGADO': 'D. PESSOAL - Restaurante',
    'SAQUE': 'D. PESSOAL - Outros',
    'SAQUE CHILE': 'D. PESSOAL - Viagens',
    'SEGURO CARRO': 'CARRO - Seguro',
    'SELAVI CONFEITARIA E C': 'D. PESSOAL - Restaurante',
    'SEM PARAR': 'CARRO - Outros',
    'SEM PARAR - PEDAGIOS': 'CARRO - Outros',
    'SERRA COPO': 'MORADIA - Manutenção/Reforma',
    'SHOPEE': 'MORADIA - Outros',
    'SHOPEE*SHOPEE PRIMEIRALIN': 'MOTO - Manutenção',
    'SIMPLES NACIONAL': 'LPC - Impostos',
    'SION POSTO DE SERVICOS': 'BARCO - Gasolina',
    'SJS AUTO POSTO': 'CARRO - Combustível',
    'SONHOS DE MARAGOG': 'D. PESSOAL - Viagens',
    'SORVETE MARAGOGI': 'D. PESSOAL - Viagens',
    'SORVETERIA PISTACHE': 'D. PESSOAL - Viagens',
    'SORVETES ROCHA': 'D. PESSOAL - Restaurante',
    'SUCESSO REDE DE RESTAU': 'D. PESSOAL - Restaurante',
    'SUPER POSTO CONST': 'MOTO - Combustível',
    'SUPERM FORTE DA B': 'MORADIA - Supermercado',
    'SUPERMERCADO CALCULA': 'MORADIA - Supermercado',
    'SUPERMERCADO GUAR': 'MORADIA - Supermercado',
    'SURF MAPPERS': 'D. PESSOAL - Esporte',
    'SWIFT': 'MORADIA - Supermercado',
    'TAXA SEMESTRAL TESOURO DIRETO': 'INVEST. - Renda Fixa',
    'TEMAKERIA TROPICAL': 'D. PESSOAL - Restaurante',
    'TEMU.COM': 'MORADIA - Outros',
    'TENTACAO PAES DOCES': 'D. PESSOAL - Restaurante',
    'TERICK CANOSSA CH': 'D. PESSOAL - Viagens',
    'THALI': 'THALI - PIX',
    'TIK TOK SHOP (CASA)': 'MORADIA - Outros',
    'TINTA P CASA': 'MORADIA - Manutenção/Reforma',
    'TJMRPANIFICADORAE': 'D. PESSOAL - Restaurante',
    'TOCCO CHICKEN': 'D. PESSOAL - Restaurante',
    'TOPSTOP': 'D. PESSOAL - Viagens',
    'TORTA FELIPE': 'D. PESSOAL - Restaurante',
    'TRANSFORMADOR E CABO': 'MORADIA - Manutenção/Reforma',
    'TRECOS': 'MORADIA - Outros',
    'TRIP SANTI': 'D. PESSOAL - Esporte',
    'TULLUM GASTROBAR': 'D. PESSOAL - Restaurante',
    'UBER': 'D. PESSOAL - Outros',
    'ULTRAFARMA POPULAR': 'D. PESSOAL - Saúde',
    'VC3 ESTACIONAMENTO': 'MOTO - Outros',
    'VIAGEM': 'D. PESSOAL - Viagens',
    'VIDRO ESCRITORIO': 'MORADIA - Manutenção/Reforma',
    'VILAR ESTACIONAMENTOS': 'CARRO - Outros',
    'VITOR - CONTADOR': 'LPC - Contador',
    'VOLTLUZ': 'MORADIA - Manutenção/Reforma',
    'VALVULA HIDRA': 'MORADIA - Manutenção/Reforma',
    'WISE TRANSFERENCIA': 'D. PESSOAL - Viagens',
    'YAE SANTOS': 'CARRO - Outros',
    'ZAE SANTOS': 'CARRO - Outros',
    'ZELO PRAIAMAR': 'MORADIA - Outros',
    'ZIG*CAFE DE LA MUSIC 1': 'D. PESSOAL - Viagens',
    'ZIG*CURVAOSURFHOUSE': 'D. PESSOAL - Restaurante',
    'ZONA AZUL SANTOS': 'CARRO - Outros',
    'ZP     *SURFMAPPERS': 'D. PESSOAL - Esporte',
    'AGUA DE COCO CALVIN': 'THALI - Calvin',
    'OLEO 2T': 'BARCO - Outros',
}

# Pré-computa chaves normalizadas uma vez
_MAPA_NORM = {_norm(k): v for k, v in MAPA_EXATO.items()}

# Regras de palavras-chave (ordem importa — mais específico primeiro)
# Tupla: (substring_normalizada, categoria)
_REGRAS = [
    # THALI — apenas menções explícitas
    ('PIX THALI', 'THALI - PIX'),
    ('THALISSA', 'THALI - PIX'),
    ('DINHEIRO EMPRESTADO', 'THALI - PIX'),
    ('COBASI', 'THALI - Calvin'),
    ('PETLOVE', 'THALI - Calvin'),
    ('PETLAND', 'THALI - Calvin'),
    ('PETZ', 'THALI - Calvin'),
    # JULI
    ('PSICOLOGA JU', 'JULI - Psicóloga'),
    ('BARCO HEITOR', 'JULI - Heitor'),
    ('PRESENTE HEITOR', 'JULI - Heitor'),
    # LPC / SAFO
    ('PAGAMENTO VITOR', 'LPC - Contador'),
    ('VITOR - CONTADOR', 'LPC - Contador'),
    ('SAFO ENG', 'SAFO ENG. - PIX'),
    ('IMPOSTOS MUNICIPAIS', 'LPC - Impostos'),
    ('IMPOSTOS SEFAZ', 'LPC - Impostos'),
    ('RECEITA FEDERAL', 'LPC - Impostos'),
    ('CERTIFICADO DIGITAL', 'LPC - Impostos'),
    ('SIMPLES NACIONAL', 'LPC - Impostos'),
    # INVEST
    ('TESOURO DIRETO', 'INVEST. - Renda Fixa'),
    ('BOLETO APTO', 'INVEST. - Casal'),
    # BARCO (mais específico antes do genérico)
    ('HOBIE', 'BARCO - Manutenção'),
    ('REPARO BARCO', 'BARCO - Manutenção'),
    ('MANUTENCAO MOTOR', 'BARCO - Manutenção'),
    ('OLEO 2T', 'BARCO - Óleo'),
    ('OLEO 4T', 'BARCO - Óleo'),
    ('GUARDARIA', 'BARCO - Guardaria'),
    # MOTO
    ('IPVA MOTO', 'MOTO - IPVA/Licenciamento'),
    ('LICENCIAMENTO MOTO', 'MOTO - IPVA/Licenciamento'),
    ('PNEU MOTO', 'MOTO - Manutenção'),
    ('PNEUS MOTO', 'MOTO - Manutenção'),
    ('REVISAO MOTO', 'MOTO - Manutenção'),
    ('CRI CRI MOTO', 'MOTO - Manutenção'),
    ('JR MOTOS', 'MOTO - Manutenção'),
    # CARRO
    ('SEGURO CARRO', 'CARRO - Seguro'),
    ('AZUL SEGUROS', 'CARRO - Seguro'),
    ('IPVA CARRO', 'CARRO - IPVA/Licenciamento'),
    ('LICENCIAMENTO CARRO', 'CARRO - IPVA/Licenciamento'),
    ('LAVA RAPIDO', 'CARRO - Lavagem'),
    ('LAVAGEM', 'CARRO - Lavagem'),
    ('FREIO CIVIC', 'CARRO - Manutenção'),
    ('FUNILARIA', 'CARRO - Manutenção'),
    ('MANUTENCAO CARRO', 'CARRO - Manutenção'),
    ('SEM PARAR', 'CARRO - Outros'),
    ('ZONA AZUL', 'CARRO - Outros'),
    ('PEDAGIO', 'CARRO - Outros'),
    ('ESTACIONAMENTO', 'CARRO - Outros'),
    ('ESTACENTER', 'CARRO - Outros'),
    ('PROL PARK', 'CARRO - Outros'),
    ('GASOLINA', 'CARRO - Combustível'),
    ('SJS AUTO POSTO', 'CARRO - Combustível'),
    ('POSTO AVENIDA', 'CARRO - Combustível'),
    ('ESTRELASANTISTA', 'CARRO - Combustível'),
    # MORADIA — Supermercado
    ('FORTE DA BARRA', 'MORADIA - Supermercado'),
    ('FORTEDABARRA', 'MORADIA - Supermercado'),
    ('ASSAI ATACADISTA', 'MORADIA - Supermercado'),
    ('PAO DE ACUCAR', 'MORADIA - Supermercado'),
    ('CARREFOUR BIG', 'MORADIA - Supermercado'),
    ('MINUTO PA', 'MORADIA - Supermercado'),
    # MORADIA — Manutenção
    ('FERRAGENS', 'MORADIA - Manutenção/Reforma'),
    ('MATERIAL DE CONSTRUCAO', 'MORADIA - Manutenção/Reforma'),
    # MORADIA — Outros
    ('TIKTOK', 'MORADIA - Outros'),
    ('ALIEXPRESS', 'D. PESSOAL - Outros'),
    # D. PESSOAL — Restaurante (ordem: mais específico antes de genérico)
    ('IFOOD', 'D. PESSOAL - Restaurante'),
    ('IFD*', 'D. PESSOAL - Restaurante'),
    ('RESTAURANTE', 'D. PESSOAL - Restaurante'),
    ('PANIFICADORA', 'D. PESSOAL - Restaurante'),
    ('PADARIA', 'D. PESSOAL - Restaurante'),
    ('PIZZA', 'D. PESSOAL - Restaurante'),
    ('BURGER', 'D. PESSOAL - Restaurante'),
    ('HAMBURGUER', 'D. PESSOAL - Restaurante'),
    ('PICANHARIA', 'D. PESSOAL - Restaurante'),
    ('CHURRASCARIA', 'D. PESSOAL - Restaurante'),
    ('CHURRASCO', 'D. PESSOAL - Restaurante'),
    ('PARRILLA', 'D. PESSOAL - Restaurante'),
    ('PARRILHA', 'D. PESSOAL - Restaurante'),
    ('ESFIHARIA', 'D. PESSOAL - Restaurante'),
    ('ESFIH', 'D. PESSOAL - Restaurante'),
    ('SUSHI', 'D. PESSOAL - Restaurante'),
    ('TEMAKERIA', 'D. PESSOAL - Restaurante'),
    ('GELATERIA', 'D. PESSOAL - Restaurante'),
    ('GASTROBAR', 'D. PESSOAL - Restaurante'),
    ('GASTRONOMIA', 'D. PESSOAL - Restaurante'),
    ('FOOD SERVICE', 'D. PESSOAL - Restaurante'),
    ('LANCHONETE', 'D. PESSOAL - Restaurante'),
    ('CONFEITARIA', 'D. PESSOAL - Restaurante'),
    ('CHOPERIA', 'D. PESSOAL - Restaurante'),
    ('CERVEJARIA', 'D. PESSOAL - Restaurante'),
    ('ACAI', 'D. PESSOAL - Restaurante'),
    ('BAR E', 'D. PESSOAL - Restaurante'),
    ('PARRILI', 'D. PESSOAL - Restaurante'),
    # D. PESSOAL — Saúde
    ('DROGARIA', 'D. PESSOAL - Saúde'),
    ('DROGASIL', 'D. PESSOAL - Saúde'),
    ('FARMACIA', 'D. PESSOAL - Saúde'),
    ('REMEDIO', 'D. PESSOAL - Saúde'),
    ('LABORATORIO', 'D. PESSOAL - Saúde'),
    ('HOSPITAL', 'D. PESSOAL - Saúde'),
    ('CLINICA', 'D. PESSOAL - Saúde'),
    ('OTICA', 'D. PESSOAL - Saúde'),
    ('ULTRAFARMA', 'D. PESSOAL - Saúde'),
    # D. PESSOAL — Outros (transporte app, não veículo próprio)
    ('UBER', 'D. PESSOAL - Outros'),
    ('99 RIDE', 'D. PESSOAL - Outros'),
    ('PG *99', 'D. PESSOAL - Outros'),
    ('DL*UBERRIDES', 'D. PESSOAL - Outros'),
    ('DL          *UBERRIDES', 'D. PESSOAL - Outros'),
    ('UBERRIDES', 'D. PESSOAL - Outros'),
    # D. PESSOAL — Viagens
    ('AIRBNB', 'D. PESSOAL - Viagens'),
    ('PASSAGEM', 'D. PESSOAL - Viagens'),
    ('DECOLAR', 'D. PESSOAL - Viagens'),
    # D. PESSOAL — Educação
    ('UDEMY', 'D. PESSOAL - Educação'),
    ('CURSO', 'D. PESSOAL - Educação'),
    # D. PESSOAL — Entretenimento
    ('CINEMA', 'D. PESSOAL - Entretenimento'),
    # D. PESSOAL — Esporte
    ('SURF MAPPERS', 'D. PESSOAL - Esporte'),
    ('MARATHON', 'D. PESSOAL - Saúde'),
]

def _classificar_por_regras(desc_norm):
    # 1) Busca exata normalizada
    if desc_norm in _MAPA_NORM:
        return _MAPA_NORM[desc_norm]

    # 2) Regras especiais de prefixo
    # PIX enviado para pessoa (formato Nubank "PIX - NOME") → outros se não for Thalissa
    if desc_norm.startswith('PIX - ') and 'THALISSA' not in desc_norm:
        return 'D. PESSOAL - Outros'
    # 99 taxi app (99*, 99 RIDE, etc.)
    if desc_norm.startswith('99'):
        return 'D. PESSOAL - Outros'

    # 3) Regras de substring
    for padrao, cat in _REGRAS:
        if padrao in desc_norm:
            return cat
    return None

def _classificar_llm(descricao):
    cats = '\n'.join(f'- {c}' for c in CATEGORIAS_VALIDAS)
    prompt = f"""Classifique o lançamento financeiro abaixo em UMA das categorias listadas.
Responda APENAS com o nome exato da categoria, sem explicação.

Lançamento: "{descricao}"

Categorias:
{cats}
"""
    try:
        resp = ollama.chat(model='llama3', messages=[{'role': 'user', 'content': prompt}])
        candidato = resp['message']['content'].strip()
        # valida se está na lista
        candidato_norm = _norm(candidato)
        for cat in CATEGORIAS_VALIDAS:
            if _norm(cat) == candidato_norm:
                return cat
        # fuzzy: checa substring
        for cat in CATEGORIAS_VALIDAS:
            if candidato_norm in _norm(cat) or _norm(cat) in candidato_norm:
                return cat
    except Exception:
        pass
    return 'D. PESSOAL - Outros'

def classificar(descricao, portador):
    port = portador.upper() if portador else ''
    resp = 'Dividido (50/50)' if 'THALISSA' in port else 'Individual (Vinicius)'

    desc_norm = _norm(descricao)
    cat = _classificar_por_regras(desc_norm)
    if cat is None:
        cat = _classificar_llm(descricao)

    return cat, resp
